### ISSUE TITLE
Where we can download dataset?

### ISSUE THREAD

**Issue by chowkamlee81** [christian-rncl/TrackNPred#1]
Where we can download dataset?

**Comment by christian-rncl** [comment]
Run setup.py on the root directory. That will download the resources folder.

**Comment by rohanchandra30** [comment]
Yes. Also note that setup.py only provides you with a single video to play around with and test the code. If you want to perform actual training and evaluation, you will need a proper larger dataset of videos.

After setting up resources folder, the instructions in the readme will tell you how and where to store videos and in what format.

Let us know if hou have any further questions

**Comment by christian-rncl** [comment]
Can I close this issue?
