### ISSUE TITLE
Missing Deep_Sort_app

### ISSUE THREAD

**Issue by Daniel-1597** [christian-rncl/TrackNPred#2]
missing a directory

**Comment by rayguan97** [comment]
Could you leave an exact error message?

**Comment by Daniel-1597** [comment]
`def parse_args():
    """ Parse command line arguments.
    """
    parser = argparse.ArgumentParser(description="Siamese Tracking")
    parser.add_argument(
        "--sequence_dir", help="Path to the MOTChallenge sequence directory.",
        default=None, required=True)
    parser.add_argument(
        "--result_file", help="Tracking output in MOTChallenge file format.",
        default=None, required=True)
    parser.add_argument(
        "--detection_file", help="Path to custom detections (optional).",
        default=None)
    parser.add_argument(
        "--update_ms", help="Time between consecutive frames in milliseconds. "
        "Defaults to the frame_rate specified in seqinfo.ini, if available.",
        default=None)
    parser.add_argument(
        "--output_file", help="Filename of the (optional) output video.",
        default=None)
    parser.add_argument(
        "--show_false_alarms", help="Show false alarms as red bounding boxes.",
        type=bool, default=False)
    return parser.parse_args()
`
this is the code in show_results.py what file i should use for each argument

**Comment by Daniel-1597** [comment]
How can we visualize the output on an image

**Comment by rayguan97** [comment]
@christian-rncl He is asking for how to get a predicted trajectory. Right now it is not implemented yet, but you are familiar with ignite framework. Can you give him some guidelines?

**Comment by rohanchandra30** [comment]
the visual results for detection and tracking are stored in resources/data in the form of image frames.

But yes, trajectory prediction results are not visual yet.

**Comment by Daniel-1597** [comment]
how can we do that?
