### ISSUE TITLE
Where is the requirements.txt ?

### ISSUE THREAD

**Issue by SpyderXu** [christian-rncl/TrackNPred#4]
This is an impressing work but I could not find the requirements.txt

**Comment by rohanchandra30** [comment]
Thanks, the developers will get back on this soon !

**Comment by rayguan97** [comment]
Run python setup.py in the root directory, you should be able to get requirements.txt installed. it is actually in "TrackNPred/model/Detection/Mask/requirements.txt".

**Comment by christian-rncl** [comment]
Did that solve your problem? Those are actually the requirements.txt for mask rcnn but I believe it’s sufficient. 

If not, we’ll upload a separate requirements.txt file

**Comment by rayguan97** [comment]
Theoretically, you only need to run python setup.py to setup everything, and that is the only requirements.txt used in the setup script. So it should be efficient. Let us know if it works or not.

**Comment by christian-rncl** [comment]
@rayguan97 I actually wrote that part of the setup.py just to setup mask-rcnn. That’s just the requirements.txt from the matterport mask repo so there’s no guarantee it will install everything.

In our instructions the part that says to install requirements.txt with pip refers to a requirements.txt that coincides with the conda environment I used when writing the first version. However that requirements.txt contained vulnerabilities from unused packages that GitHub kept flagging so I removed it from the repo.

**Comment by rohanchandra30** [comment]
From what another user told me, they did the setup.py and then there were several packages that they had to manually install when they kept encountering the corresponding error messages for those packages. 

@christian-rncl No rush for this ticket. Whenever you get the chance, upload the new requirements file. In the meantime @SpyderXu do the setup.py and then install the requirements manually for now, till we get a requirements.txt file uploaded.

**Comment by christian-rncl** [comment]
Just uploaded a new one, I would try that
